### ISSUE TITLE
TypeError: pc.magentaBright is not a function when using v2.0.2

### ISSUE THREAD

**Issue by luo772435545** [crxjs/chrome-extension-tools#1043]
### Build tool

Vite

### Where do you see the problem?

- [x] In the browser
- [ ] In the terminal

### Describe the bug

Hi, I'm encountering the following error when upgrading @crxjs/vite-plugin from 2.0.0-beta.26 to 2.0.2:

`error when starting dev server:
TypeError: pc.magentaBright is not a function
    at printStr (.../node_modules/@crxjs/vite-plugin/dist/index.mjs:1274:18)
    at server.printUrls (.../node_modules/@crxjs/vite-plugin/dist/index.mjs:1291:23)
`

### Reproduction

-

### Logs

```shell

```

### System Info

```shell
browser
```

### Severity

annoyance

**Comment by Toumash** [comment]
duplicate of #1038
